# I will figure out these datetimes if it's the last thing I do

In [1]:
# imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

## Parse DateTimes

### Activity

In [20]:
# load in cleaned data
activity_path = "CSCI413Project/cleaned data/Activity Data Cleaned.csv"
activity_df = pd.read_csv(activity_path)
activity_df.head()

,activity_ts,activity_type,active_Kcal,step_count,distance_m,duration_s,active_time_s,start_time_s,start_time_offset_s,met,intensity,motion_intensity_mean,motion_intensity_max,subjectID
0,2023-10-01 05:45:00,SEDENTARY,0,0,0.0,900,900,1696135500,3600,1.0,SEDENTARY,0.0,2.0,2301
1,2023-10-01 06:00:00,SEDENTARY,0,0,0.0,900,900,1696136400,3600,1.0,SEDENTARY,0.0,1.0,2301
2,2023-10-01 06:15:00,SEDENTARY,0,0,0.0,900,900,1696137300,3600,1.0,SEDENTARY,0.0,3.0,2301
3,2023-10-01 06:30:00,SEDENTARY,0,0,0.0,900,900,1696138200,3600,1.0,SEDENTARY,0.0,4.0,2301
4,2023-10-01 06:45:00,SEDENTARY,0,0,0.0,900,900,1696139100,3600,1.0,SEDENTARY,0.0,3.0,2301

In [21]:
# convert to datetime object
activity_df["activity_ts"] = pd.to_datetime(activity_df["activity_ts"], format="%Y-%m-%d %H:%M:%S")
activity_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228485 entries, 0 to 228484
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   activity_ts            228485 non-null  datetime64[ns]
 1   activity_type          228485 non-null  object
 2   active_Kcal            228485 non-null  int64
 3   step_count             228485 non-null  int64
 4   distance_m             228485 non-null  float64
 5   duration_s             228485 non-null  int64
 6   active_time_s          228485 non-null  int64
 7   start_time_s           228485 non-null  int64
 8   start_time_offset_s    228485 non-null  int64
 9   met                    228485 non-null  float64
 10  intensity              228485 non-null  object
 11  motion_intensity_mean  228485 non-null  float64
 12  motion_intensity_max   228485 non-null  float64
 13  subjectID              228485 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(7), object(2)
memory usage: 24.4+ MB

### Nutrition

In [32]:
# load in cleaned data
nutrition_path = "CSCI413Project/cleaned data/Nutrition Data Cleaned.csv"
nutrition_df = pd.read_csv(nutrition_path)
nutrition_df.head()

            meal_ts  meal_type  carbs_g  prot_g  fat_g  subjectID
0  22/10/2023 10:00  Breakfast      0.0     0.0    1.0       2301
1  22/10/2023 12:00      Lunch     19.0    50.0   32.0       2301
2  22/10/2023 17:15     Dinner     10.0    30.0   25.0       2301
3  23/10/2023 00:00  Breakfast      0.0     0.0    1.0       2301
4  23/10/2023 14:49      Lunch     54.0    22.0   30.0       2301

In [33]:
# clean time stamp
# nutrition_df.drop(nutrition_df[ len(nutrition_df["meal_ts"]) > len(nutrition_df["meal_ts"][0]) ].index, inplace=True)

In [35]:
# convert to datetime object
nutrition_df["meal_ts"] = pd.to_datetime(nutrition_df["meal_ts"], dayfirst=True, format="mixed")#format="%d/%m/%Y %H:%M")
nutrition_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4309 entries, 0 to 4308
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   meal_ts    4309 non-null   datetime64[ns]
 1   meal_type  4309 non-null   object
 2   carbs_g    4309 non-null   float64
 3   prot_g     4309 non-null   float64
 4   fat_g      4309 non-null   float64
 5   subjectID  4309 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 202.1+ KB

### Sleep

In [31]:
# load in cleaned data
sleep_path = "CSCI413Project/cleaned data/Sleep Data Cleaned.csv"
sleep_df = pd.read_csv(sleep_path)
sleep_df.head()

,sleep_ts,heart_rate,current_activity_type_intensity,stress_level_value,sleep_level,resting_heart_rate,subjectID
0,2023-10-06 00:05:00,83,8,29,0,0,2301
1,2023-10-06 00:10:00,82,0,33,0,0,2301
2,2023-10-06 00:15:00,83,0,31,0,0,2301
3,2023-10-06 00:20:00,82,0,31,0,0,2301
4,2023-10-06 00:25:00,87,0,-1,0,0,2301

In [36]:
# convert to datetime object
sleep_df["sleep_ts"] = pd.to_datetime(sleep_df["sleep_ts"], format="%Y-%m-%d %H:%M:%S")
sleep_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304658 entries, 0 to 304657
Data columns (total 7 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   sleep_ts                         304658 non-null  datetime64[ns]
 1   heart_rate                       304658 non-null  int64
 2   current_activity_type_intensity  304658 non-null  int64
 3   stress_level_value               304658 non-null  int64
 4   sleep_level                      304658 non-null  int64
 5   resting_heart_rate               304658 non-null  int64
 6   subjectID                        304658 non-null  int64
dtypes: datetime64[ns](1), int64(6)
memory usage: 16.3 MB

### Activity (combining and stuff)

In [37]:
activity_df.head()

,activity_ts,activity_type,active_Kcal,step_count,distance_m,duration_s,active_time_s,start_time_s,start_time_offset_s,met,intensity,motion_intensity_mean,motion_intensity_max,subjectID
0,2023-10-01 05:45:00,SEDENTARY,0,0,0.0,900,900,1696135500,3600,1.0,SEDENTARY,0.0,2.0,2301
1,2023-10-01 06:00:00,SEDENTARY,0,0,0.0,900,900,1696136400,3600,1.0,SEDENTARY,0.0,1.0,2301
2,2023-10-01 06:15:00,SEDENTARY,0,0,0.0,900,900,1696137300,3600,1.0,SEDENTARY,0.0,3.0,2301
3,2023-10-01 06:30:00,SEDENTARY,0,0,0.0,900,900,1696138200,3600,1.0,SEDENTARY,0.0,4.0,2301
4,2023-10-01 06:45:00,SEDENTARY,0,0,0.0,900,900,1696139100,3600,1.0,SEDENTARY,0.0,3.0,2301